-- Execute este código no SQL Editor do Supabase.

create table public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) >= 2),
  descricao text,
  preco numeric(10,2) not null check (preco >= 0),
  estoque integer not null default 0 check (estoque >= 0),
  imagem_url text,
  criado_em timestamptz not null default now()
);

alter table public.produtos enable row level security;

create policy "Produtos visíveis para todos" on public.produtos for select using (true);
create policy "Usuários autenticados cadastram produtos" on public.produtos for insert to authenticated with check (true);
create policy "Usuários autenticados editam produtos" on public.produtos for update to authenticated using (true) with check (true);
create policy "Usuários autenticados excluem produtos" on public.produtos for delete to authenticated using (true);

insert into public.produtos (nome, descricao, preco, estoque, imagem_url) values
('Bolsa Essencial', 'Bolsa minimalista para todas as ocasiões.', 189.90, 8, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80'),
('Tênis Urbano', 'Conforto e estilo para a rotina.', 249.90, 12, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'),
('Relógio Clássico', 'Design elegante e acabamento sofisticado.', 329.90, 5, 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80');
